@push_token_id = 123
@device_token = sample_device_token_here

### Get push tokens list
GET {{base_url}}/push_tokens HTTP/1.1
    ?limit=10
    &offset=0
    &sort=id.desc
Authorization: Bearer {{token}}
Content-Type: application/json

### Create push token
POST {{base_url}}/push_tokens HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "device_token": "{{device_token}}",
  "device_type": "ios",
  "app_version": "1.0.0"
}

### Delete push token
DELETE {{base_url}}/push_tokens/{{push_token_id}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
