@limit = 10
@q = onur@hipcall.com
@user_id = 2945


### Get user list
GET {{base_url}}/users?limit={{limit}}&offset=0&q={{q}}&sort=id.asc HTTP/1.1
Authorization: Bearer {{token}}

### Get user by id
GET {{base_url}}/users/{{user_id}} HTTP/1.1
Authorization: Bearer {{token}}

### Update user with put method
PUT {{base_url}}/users/{{user_id}} HTTP/1.1
Authorization: Bearer {{token}}

{
    "default_number": 8508850226
}

### Update user with patch method
PATCH {{base_url}}/users/{{user_id}} HTTP/1.1
Authorization: Bearer {{token}}

{
    "default_number": 8508850226
}
