@company_id = 66336
@contact_id = 49775
@email = xfirm@bfpratik.com
@limit = 10
@offset = 0
@phone_number = +908508850227
@sort = id.asc
@tag_id = 5417
@user_id = 2945

### Get companies list
GET {{base_url}}/companies?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}

### Create company
POST {{base_url}}/companies HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "assign_to_user_id": {{user_id}},
  "custom_url": "https://custom.com #{{$timestamp}}",
  "description": "This is a test description for the company #{{$timestamp}}",
  "emails": [
    {
      "email": "info@microsoft.com #{{$timestamp}}"
    }
  ],
  "linkedin_url": "https://linkedin.com/company/microsoft #{{$timestamp}}",
  "name": "Microsoft Inc #{{$timestamp}}",
  "phones": [
    {
      "country": "US",
      "number": "+1 (425) 882-8080 #{{$timestamp}}"
    }
  ],
  "website_url": "https://microsoft.com #{{$timestamp}}"
}


### Get companies comments
GET {{base_url}}/companies/{{company_id}}/comments?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}


### Create company comment
POST {{base_url}}/companies/{{company_id}}/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Created comment for company #{{$timestamp}}"
}

### Add email addresses to a company
POST {{base_url}}/companies/{{company_id}}/emails HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "emails": [
    "{{email}}"
  ]
}

### Delete email addresses from a company
DELETE {{base_url}}/companies/{{company_id}}/emails/{{email}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "emails": [
    "{{email}}"
  ]
}

### Add phone numbers to company
POST {{base_url}}/companies/{{company_id}}/phones HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "numbers": [
    "{{phone_number}}"
  ]
}

### Delete phone numbers from company
DELETE {{base_url}}/companies/{{company_id}}/phones/{{phone_number}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "numbers": [
    "{{phone_number}}"
  ]
}

### Get company tag
GET {{base_url}}/companies/{{company_id}}/tags?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}

### Add tag to company
POST {{base_url}}/companies/{{company_id}}/tags HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "tag_id": {{tag_id}}
}

### Remove tag from company
DELETE {{base_url}}/companies/{{company_id}}/tags/{{tag_id}} HTTP/1.1
Authorization: Bearer {{token}}

### Get companies list with id
GET {{base_url}}/companies/{{company_id}}?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1 
Authorization: Bearer {{token}}

### Assign company to user with patch method
PATCH {{base_url}}/companies/{{company_id}}/assign HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "assign_to_user_id": {{user_id}}
}

### Get contact list
GET {{base_url}}/contacts?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}

### Create contact
POST {{base_url}}/contacts HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "assign_to_user_id": {{user_id}},
  "company_id": {{company_id}},
  "custom_url": "https://custom.com #{{$timestamp}}",
  "emails": [
    {
      "email": "info@microsoft.com #{{$timestamp}}"
    }
  ],
  "first_name": "Bill #{{$timestamp}}",
  "job_title": "Co-founder #{{$timestamp}}",
  "last_name": "Gates #{{$timestamp}}",
  "linkedin_url": "https://linkedin.com/in/williamhgates #{{$timestamp}}",
  "phones": [
    {
      "country": "US",
      "number": "+1 (425) 882-8080 #{{$timestamp}}"
    }
  ]
}'
### Get contacts comments
GET {{base_url}}/contacts/{{contact_id}}/comments?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}

### Create contacts comments
POST {{base_url}}/contacts/{{contact_id}}/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "This is a test comment for the contact #{{$timestamp}}"
}

### Add email addresses to a contact
POST {{base_url}}/contacts/{{contact_id}}/emails HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "emails": [
    "{{email}}"
  ]
}

### Delete email addresses from a contact
DELETE {{base_url}}/contacts/{{contact_id}}/emails/{{email}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "emails": [
    "{{email}}"
  ]
}

### Add phone numbers to a contact
POST {{base_url}}/contacts/{{contact_id}}/phones HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "numbers": [
    "{{phone_number}}"
  ]
}

### Delete phone numbers from a contact
DELETE {{base_url}}/contacts/{{contact_id}}/phones/{{phone_number}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "numbers": [
    "{{phone_number}}"
  ]
}
### Get contact tags
GET {{base_url}}/contacts/{{contact_id}}/tags?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}

### Add tag to contact
POST {{base_url}}/contacts/{{contact_id}}/tags HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "tag_id": {{tag_id}}
}

### Remove tag from contact
DELETE {{base_url}}/contacts/{{contact_id}}/tags/{{tag_id}} HTTP/1.1
Authorization: Bearer {{token}}

### Get contact with id
GET {{base_url}}/contacts/{{contact_id}}?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}

### Assign contact to user with patch method
PATCH {{base_url}}/contacts/{{contact_id}}/assign HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "assign_to_user_id": {{user_id}}
}

###Lookup by email
GET {{base_url}}/lookup/by_email?email={{email}} HTTP/1.1
Authorization: Bearer {{token}}

### Lookup by phone
GET {{base_url}}/lookup/by_phone?number={{phone_number}} HTTP/1.1
Authorization: Bearer {{token}}
