@deal_id = 5968
@limit = 10
@offset = 0
@q = Deal
@sort = id.asc

### Get deal list
GET {{base_url}}/deals?limit={{limit}}&offset={{offset}}&q={{q}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

### Get deals comments
GET {{base_url}}/deals/{{deal_id}}/comments?limit={{limit}}&offset={{offset}}&sort={{sort}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

### Create deal comment
POST {{base_url}}/deals/{{deal_id}}/comments HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "content": "This is a test comment for the deal #{{$timestamp}}"
}

### Get deal with id
GET {{base_url}}/deals/{{deal_id}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: application/json
